### ISSUE TITLE
What is the Use of app group extension ?

### ISSUE THREAD

**Issue by zulfiker** [DeluxeAlonso/UpcomingMovies#555]
Hi . This is not exactly an issue .I am just trying to understanding your codebase as i think it is well written . i am curious about one part . what is the use of **AppGroup** Enum ?  I am seeing it is being used in **LocalDataSource** class . May be it is not as complicated but i am missing the point . can you please explain your thinking ? thanks

**Comment by DeluxeAlonso** [comment]
Hi @zulfiker, thanks for your question. AppGroup is basically used for CoreData database sharing purposes. In our use case, we want a shared database between the main app and the Today extension (Today extension is currently deprecated).

If you check the configurations for both the main app and today extension target you will see that we have the app group specified in the enum defined there:

<img width="724" alt="Screen Shot 2022-09-11 at 10 48 23" src="https://user-images.githubusercontent.com/9066633/189536842-24dce3b0-bd1a-4733-aba8-e637b19d4132.png">

We use that group identifier to initialize the core data stack from the main app and the today extension.

You can read more about this approach here:  https://www.avanderlee.com/swift/core-data-app-extension-data-sharing/

Is important to note that since iOS 13 this is the recommended approach: https://www.avanderlee.com/swift/persistent-history-tracking-core-data/
I will probably update it in the app in a near future.

Feel free to post if you have any other questions or concerns.

**Comment by zulfiker** [comment]
hi @DeluxeAlonso  thanks for your detail answer . I am trying to understanding your codebase as it is both interesting and well organised . if you dont mind i may come with some more questions later just understand your design decision from your point of view . thanks again

**Comment by DeluxeAlonso** [comment]
@zulfiker thanks to you. Sure, if you have any other question dont hesitate to contact me. You can open a new issue.
